id: http://w3id.org/mixs/food_farm_environment
name: food_farm_environment
imports:
- linkml:types
- terms
prefixes:
  linkml: https://w3id.org/linkml/
  mixs.vocab: https://w3id.org/mixs/vocab/
  MIXS: https://w3id.org/mixs/terms/
default_prefix: mixs.vocab
slots: {}
classes:
  food-farm environment:
    description: food-farm environment
    mappings: []
    slots:
    - lat_lon
    - depth
    - alt
    - elev
    - temp
    - geo_loc_name
    - collection_date
    - env_broad_scale
    - env_local_scale
    - env_medium
    - cult_result
    - samp_purpose
    - food_quality_date
    - soil_texture_class
    - tillage
    - extr_weather_event
    - food_clean_proc
    - growth_habit
    - farm_water_source
    - water_source_shared
    - air_flow_impede
    - plant_reprod_crop
    - crop_rotation
    - samp_stor_dur
    - ph
    - root_med_ph
    - soil_pH
    - timepoint
    - water_pH
    - conduc
    - host_age
    - host_dry_mass
    - host_height
    - host_length
    - host_tot_mass
    - humidity
    - salinity
    - samp_stor_temp
    - season_humidity
    - season_precpt
    - season_temp
    - size_frac_low
    - size_frac_up
    - soil_conductivity
    - solar_irradiance
    - tot_nitro_content
    - turbidity
    - ventilation_rate
    - wind_speed
    - crop_yield
    - soil_temp
    - water_frequency
    - animal_group_size
    - lot_number
    - intended_consumer
    - host_taxid
    - soil_porosity
    - tot_org_carb
    - genetic_mod
    - ph_meth
    - salinity_meth
    - soil_texture_meth
    - soil_type_meth
    - tot_nitro_cont_meth
    - tot_org_c_meth
    - enrichment_protocol
    - root_cond
    - host_subspecf_genlin
    - plant_part_maturity
    - anim_water_method
    - animal_housing
    - farm_equip
    - farm_equip_shared
    - fertilizer_admin
    - food_source
    - food_trav_mode
    - plant_water_method
    - samp_source_mat_cat
    - samp_type
    - season
    - soil_cover
    - soil_type
    - plant_growth_med
    - chem_administration
    - animal_intrusion
    - cult_result_org
    - cult_target
    - serovar_or_serotype
    - spikein_org
    - spikein_serovar
    - spikein_strain
    - samp_collect_device
    - adjacent_environment
    - animal_feed_equip
    - ances_data
    - animal_diet
    - biotic_regm
    - farm_equip_san_freq
    - food_harvest_proc
    - food_prod_char
    - growth_medium
    - host_genotype
    - IFSAC_category
    - library_prep_kit
    - prod_label_claims
    - rel_location
    - repository_name
    - samp_pooling
    - sequencing_kit
    - sequencing_location
    - ventilation_type
    - water_source_adjac
    - wind_direction
    - farm_equip_san
    - spikein_antibiotic
    - spikein_metal
    - air_PM_concen
    - misc_param
    - root_med_carbon
    - root_med_macronutr
    - root_med_micronutr
    - organism_count
    - spikein_count
    - perturbation
    - host_phenotype
    - mechanical_damage
    - previous_land_use
    - food_contact_surf
    - food_contain_wrap
    - food_pack_medium
    - food_preserv_proc
    - food_product_type
    - food_trav_vehic
    - food_treat_proc
    - part_plant_animal
    - spikein_growth_med
    - cult_isol_date
    - date_extr_weath
    - fertilizer_date
    slot_usage:
      cult_result:
        required: false
      samp_purpose:
        required: false
      food_quality_date:
        required: false
      soil_texture_class:
        required: false
      tillage:
        required: false
      extr_weather_event:
        required: false
      food_clean_proc:
        required: false
      growth_habit:
        required: false
      farm_water_source:
        required: false
      water_source_shared:
        required: false
      air_flow_impede:
        required: false
      plant_reprod_crop:
        required: false
      crop_rotation:
        required: false
      samp_stor_dur:
        required: false
      ph:
        required: false
      root_med_ph:
        required: false
      soil_pH:
        required: false
      timepoint:
        required: false
      water_pH:
        required: false
      lat_lon:
        required: true
      conduc:
        required: false
      depth:
        required: true
      host_age:
        required: false
      host_dry_mass:
        required: false
      host_height:
        required: false
      host_length:
        required: false
      host_tot_mass:
        required: false
      humidity:
        required: false
      salinity:
        required: false
      samp_size:
        required: false
      samp_stor_temp:
        required: false
      samp_vol_we_dna_ext:
        required: false
      season_humidity:
        required: false
      season_precpt:
        required: false
      season_temp:
        required: false
      size_frac_low:
        required: false
      size_frac_up:
        required: false
      soil_conductivity:
        required: false
      solar_irradiance:
        required: false
      temp:
        required: false
      tot_nitro_content:
        required: false
      turbidity:
        required: false
      ventilation_rate:
        required: false
      wind_speed:
        required: false
      crop_yield:
        required: false
      soil_temp:
        required: false
      water_frequency:
        required: false
      animal_group_size:
        required: false
      lot_number:
        required: false
      intended_consumer:
        required: false
      host_taxid:
        required: false
      soil_porosity:
        required: false
      tot_org_carb:
        required: false
      genetic_mod:
        required: false
      nucl_acid_ext:
        required: false
      ph_meth:
        required: false
      salinity_meth:
        required: false
      soil_texture_meth:
        required: false
      soil_type_meth:
        required: false
      tot_nitro_cont_meth:
        required: false
      tot_org_c_meth:
        required: false
      enrichment_protocol:
        required: false
      root_cond:
        required: false
      host_subspecf_genlin:
        required: false
      plant_part_maturity:
        required: false
      geo_loc_name:
        required: true
      anim_water_method:
        required: false
      animal_housing:
        required: false
      env_broad_scale:
        required: true
      env_local_scale:
        required: true
      env_medium:
        required: true
      farm_equip:
        required: false
      farm_equip_shared:
        required: false
      fertilizer_admin:
        required: false
      food_source:
        required: false
      food_trav_mode:
        required: false
      plant_water_method:
        required: false
      samp_source_mat_cat:
        required: false
      samp_type:
        required: true
      season:
        required: false
      soil_cover:
        required: false
      soil_type:
        required: false
      plant_growth_med:
        required: false
      chem_administration:
        required: true
      animal_intrusion:
        required: false
      cult_result_org:
        required: false
      cult_target:
        required: false
      serovar_or_serotype:
        required: false
      spikein_org:
        required: false
      spikein_serovar:
        required: false
      spikein_strain:
        required: false
      samp_collect_device:
        required: false
      seq_meth:
        required: true
      adjacent_environment:
        required: false
      animal_feed_equip:
        required: false
      ances_data:
        required: false
      animal_diet:
        required: false
      biotic_regm:
        required: true
      farm_equip_san_freq:
        required: false
      food_harvest_proc:
        required: false
      food_prod_char:
        required: false
      growth_medium:
        required: false
      host_genotype:
        required: false
      IFSAC_category:
        required: true
      library_prep_kit:
        required: false
      prod_label_claims:
        required: false
      project_name:
        required: true
      rel_location:
        required: false
      repository_name:
        required: false
      samp_name:
        required: true
      samp_pooling:
        required: false
      sequencing_kit:
        required: false
      sequencing_location:
        required: false
      ventilation_type:
        required: false
      water_source_adjac:
        required: false
      wind_direction:
        required: false
      farm_equip_san:
        required: false
      spikein_antibiotic:
        required: false
      spikein_metal:
        required: false
      air_PM_concen:
        required: false
      misc_param:
        required: false
      root_med_carbon:
        required: false
      root_med_macronutr:
        required: false
      root_med_micronutr:
        required: false
      organism_count:
        required: false
      spikein_count:
        required: false
      perturbation:
        required: false
      host_phenotype:
        required: false
      mechanical_damage:
        required: false
      previous_land_use:
        required: false
      food_contact_surf:
        required: false
      food_contain_wrap:
        required: false
      food_pack_medium:
        required: false
      food_preserv_proc:
        required: false
      food_product_type:
        required: true
      food_trav_vehic:
        required: false
      food_treat_proc:
        required: false
      host_disease_stat:
        required: false
      part_plant_animal:
        required: false
      spikein_growth_med:
        required: false
      collection_date:
        required: true
      cult_isol_date:
        required: false
      date_extr_weath:
        required: false
      fertilizer_date:
        required: false
subsets: {}
enums: {}
