id: http://w3id.org/mixs/miscellaneous_natural_or_artificial_environment
name: miscellaneous_natural_or_artificial_environment
imports:
- linkml:types
- terms
prefixes:
  linkml: https://w3id.org/linkml/
  mixs.vocab: https://w3id.org/mixs/vocab/
  MIXS: https://w3id.org/mixs/terms/
default_prefix: mixs.vocab
slots: {}
classes:
  miscellaneous natural or artificial environment:
    description: miscellaneous natural or artificial environment
    mappings: []
    slots:
    - lat_lon
    - depth
    - alt
    - elev
    - temp
    - geo_loc_name
    - collection_date
    - env_broad_scale
    - env_local_scale
    - env_medium
    - alkalinity
    - ammonium
    - biomass
    - bromide
    - calcium
    - chem_administration
    - chloride
    - chlorophyll
    - density
    - diether_lipids
    - diss_carb_dioxide
    - diss_hydrogen
    - diss_inorg_carb
    - diss_org_nitro
    - diss_oxygen
    - misc_param
    - nitrate
    - nitrite
    - nitro
    - org_carb
    - org_matter
    - org_nitro
    - organism_count
    - oxy_stat_samp
    - ph
    - perturbation
    - phosphate
    - phosplipid_fatt_acid
    - potassium
    - pressure
    - salinity
    - samp_store_dur
    - samp_store_loc
    - samp_store_temp
    - silicate
    - sodium
    - sulfate
    - sulfide
    - water_current
    slot_usage:
      samp_name:
        required: true
      project_name:
        required: true
      alt:
        required: false
      depth:
        required: false
      elev:
        required: false
      alkalinity:
        required: false
      ammonium:
        required: false
      biomass:
        required: false
      bromide:
        required: false
      calcium:
        required: false
      chem_administration:
        required: false
      chloride:
        required: false
      chlorophyll:
        required: false
      density:
        required: false
      diether_lipids:
        required: false
      diss_carb_dioxide:
        required: false
      diss_hydrogen:
        required: false
      diss_inorg_carb:
        required: false
      diss_org_nitro:
        required: false
      diss_oxygen:
        required: false
      misc_param:
        required: false
      nitrate:
        required: false
      nitrite:
        required: false
      nitro:
        required: false
      org_carb:
        required: false
      org_matter:
        required: false
      org_nitro:
        required: false
      organism_count:
        required: false
      oxy_stat_samp:
        required: false
      ph:
        required: false
      perturbation:
        required: false
      phosphate:
        required: false
      phosplipid_fatt_acid:
        required: false
      potassium:
        required: false
      pressure:
        required: false
      salinity:
        required: false
      samp_store_dur:
        required: false
      samp_store_loc:
        required: false
      samp_store_temp:
        required: false
      samp_vol_we_dna_ext:
        required: false
      silicate:
        required: false
      sodium:
        required: false
      sulfate:
        required: false
      sulfide:
        required: false
      temp:
        required: false
      water_current:
        required: false
subsets: {}
enums: {}
