extends: recommended
rules:
  recommended:
    level: error
    exclude_type:
      - enum_definition
  standard_naming:
    level: error
    exclude_type:
      - permissible_value
    exclude:
      - HACCP_term
      - IFSAC_category
      - air_PM_concen
      - microb_start_taxID
      - spikein_AMR
      - ferm_pH
      - soil_pH
      - water_pH