rules:
  standard_naming:
    level: disabled # want to ignore permissible values
    #    class_pattern:
    #    slot_pattern:
    permissible_values_upper_case: false
  canonical_prefixes:
    level: error
    prefixmaps_contexts:
      - merged
    #      - bioportal
    #      - bioregistry
    #      - bioregistry.upper
    #      - go
    #      - linked_data
    #      - merged.monarch
    #      - merged.oak
    #      - obo
    #      - prefixcc
    #      - w3id
  no_empty_title:
    level: disabled # want to ignore enums
  no_invalid_slot_usage:
    level: error
  no_xsd_int_type:
    level: error
  permissible_values_format:
    level: error
    format: '[a-zA-Z0-9\-\_\.\~ ]*'
  recommended:
    level: error
    exclude:
      - AeroStrucEnum
      - AnimalBodyCondEnum
      - AnimalSexEnum
      - ArchStrucEnum
      - AssemblyQualEnum
      - BinParamEnum
      - BiolStatEnum
      - BioticRelationshipEnum
      - BuildDocsEnum
      - BuildingSettingEnum
      - BuildOccupTypeEnum
      - BuiltStrucSetEnum
      - CeilFinishMatEnum
      - CeilingWallTextureEnum
      - CeilStrucEnum
      - CeilTypeEnum
      - CompassDirections8Enum
      - ComplApprEnum
      - ContamScreenInputEnum
      - CultResultEnum
      - DamagedEnum
      - DamagedRupturedEnum
      - DeposEnvEnum
      - DominantHandEnum
      - DoorCompTypeEnum
      - DoorDirectEnum
      - DoorMatEnum
      - DoorMoveEnum
      - DoorTypeEnum
      - DoorTypeMetalEnum
      - DrainageClassEnum
      - DrawingsEnum
      - ExtrWeatherEventEnum
      - FacilityTypeEnum
      - FaoClassEnum
      - FarmWaterSourceEnum
      - FilterTypeEnum
      - FireplaceTypeEnum
      - FloorStrucEnum
      - FloorWaterMoldEnum
      - FoodCleanProcEnum
      - FoodTraceListEnum
      - FreqCleanEnum
      - FurnitureEnum
      - GenderRestroomEnum
      - GeolAgeEnum
      - GrowthHabitEnum
      - HandidnessEnum
      - HcProducedEnum
      - HcrEnum
      - HeatCoolTypeEnum
      - HeatSysDelivMethEnum
      - HostCellularLocEnum
      - HostDependenceEnum
      - HostPredApprEnum
      - HostSpecificityEnum
      - IndoorSpaceEnum
      - IndoorSurfEnum
      - LibLayoutEnum
      - LightTypeEnum
      - LithologyEnum
      - MagCovSoftwareEnum
      - MechStrucEnum
      - ModeTransmissionEnum
      - MoldVisibilityEnum
      - NegContTypeEnum
      - OccupDocumentEnum
      - OxyStatSampEnum
      - PlantReprodCropEnum
      - PlantSexEnum
      - PredGenomeStrucEnum
      - ProfilePositionEnum
      - QuadPosEnum
      - RelSampLocEnum
      - RelToOxygenEnum
      - RoomCondtEnum
      - RoomConnectedEnum
      - RoomLocEnum
      - RoomSampPosEnum
      - RoomTypeEnum
      - RouteTransmissionEnum
      - SampCaptStatusEnum
      - SampCollectPointEnum
      - SampDisStageEnum
      - SampLocConditionEnum
      - SampPurposeEnum
      - SampSubtypeEnum
      - SampSurfMoistureEnum
      - SampTransportContEnum
      - SampWeatherEnum
      - ScLysisApproachEnum
      - SeasonUseEnum
      - SedimentTypeEnum
      - SeqQualityCheckEnum
      - ShadingDeviceLocEnum
      - ShadingDeviceTypeEnum
      - SoilHorizonEnum
      - SoilTextureClassEnum
      - SortTechEnum
      - SpaceTypStateEnum
      - SpecificEnum
      - SrDepEnvEnum
      - SrKerogTypeEnum
      - SrLithologyEnum
      - SubstructureTypeEnum
      - SurfAirContEnum
      - SurfMaterialEnum
      - SymbiontHostRoleEnum
      - SymLifeCycleTypeEnum
      - TaxIdentEnum
      - TidalStageEnum
      - TillageEnum
      - TrainLineEnum
      - TrainStatLocEnum
      - TrainStopLocEnum
      - TrophicLevelEnum
      - TypeOfSymbiosisEnum
      - UrineCollectMethEnum
      - UrobiomSexEnum
      - ViralGenomeTypeEnum
      - VirusEnrichApprEnum
      - WallConstTypeEnum
      - WallFinishMatEnum
      - WallSurfTreatmentEnum
      - WaterFeatTypeEnum
      - WeekdayEnum
      - WgaAmpApprEnum
      - WindowCoverEnum
      - WindowHorizPosEnum
      - WindowMatEnum
      - WindowStatusEnum
      - WindowTypeEnum
      - WindowVertPosEnum
  tree_root_class:
    level: error
    root_class_name: MixsCompliantData
    validate_existing_class_name: true

# all levels can be set to disabled, error or warning
