extends: recommended
rules:
  recommended:
    level: error
    exclude_type:
      - enum_definition
    exclude:
      - combination_classes
      - sequencing
      - environment
      - nucleic acid sequence source
      - investigation
  standard_naming:
    level: error
    exclude_type:
      - permissible_value
    exclude:
      - HACCP_term
      - IFSAC_category
      - air_PM_concen
      - ferm_pH
      - microb_start_taxID
      - soil_pH
      - spikein_AMR
      - water_pH
