language: node_js
node_js:
  - '7'
before_install: 
- npm install ajv
- npm install -g ajv-cli
script:
- ajv validate -s mixs-schema.json -d mixs.json
cache:
  directories:
    - node_modules
sudo: false
