site_name: "MIxS"
theme:
  name: readthedocs
#  analytics:
#    gtag: G-2SYBSJVZ23
docs_dir: generated/docs
site_dir: docs
#nav:
#  - Index: index.md
site_url: https://genomicsstandardsconsortium.github.io/mixs/
repo_url: https://github.com/GenomicsStandardsConsortium/mixs
