site_name: "MIxS"

theme:
  name: material
  nav_style: dark

plugins:
  - search

docs_dir: schemasheets/generated/docs
site_dir: schemasheets/mkdocs_html

#nav:
#  - Reference: index.md
#  - Introduction:
#    - Background: introduction/background.md
#    - Cite: introduction/citation.md
#    - Contents: introduction/contents.md

#site_url: https://genomicsstandardsconsortium.github.io/mixs/
#repo_url: https://github.com/GenomicsStandardsConsortium/mixs/
