---
site_name: "mixs-6-2-for-merge"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://GenomicsStandardsConsortium.github.io/mixs-6-2-for-merge
repo_url: https://github.com/GenomicsStandardsConsortium/mixs-6-2-for-merge

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
