site_name: "MIxS"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
docs_dir: target/docs
site_dir: docs
nav:
  - Index: index.md
site_url: https://cmungall.github.io/mixs-source/
repo_url: https://github.com/cmungall/mixs-source
