site_name: "LinkML Documentation for Proposed MIxS 6.2"
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - "- MIxS v6.2.rc Documentation Home": index.md
  - "- Ephemeral, un-submitted validation": __data_harmonizer/
  - "- Back to GitHub repository": https://github.com/microbiomedata/mixs-6-2-release-candidate


site_url: https://microbiomedata.github.io/mixs-6-2-release-candidate/
repo_url: https://github.com/microbiomedata/mixs-6-2-release-candidate

docs_dir: mixs-docs-md
