site_name: "MIxS from Schemasheets"

theme:
  name: material
  nav_style: dark

plugins:
  - search

docs_dir: schemasheets/generated/gen_docs_docs
site_dir: schemasheets/mkdocs_html

nav:
  - Reference: index.md
  - Introduction:
    - Background: introduction/background.md
    - Cite: introduction/citation.md
    - Contents: introduction/contents.md

site_url: https://genomicsstandardsconsortium.github.io/mixs/
repo_url: https://github.com/GenomicsStandardsConsortium/mixs/
