"""Every file that carries a MIxS version string must carry the same one.

The release action writes the version into some of these with `sed -i`, which exits
0 whether or not its pattern matched. If one of these files is reformatted, the sed
silently changes nothing and the release ships a stale version with no error. The
rest inherit the version from src/mixs/schema/mixs.yaml when `make` regenerates them,
so they only disagree if a build was skipped or partial.

pyproject.toml is excluded on purpose: it holds a 0.0.0 placeholder and the Python
package version comes from the git tag at build time.
"""

import json
import re
import unittest
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

SOURCE_SCHEMA = ROOT / "src" / "mixs" / "schema" / "mixs.yaml"


def schema_version():
    return str(yaml.safe_load(SOURCE_SCHEMA.read_text())["version"])


def from_yaml_key(path, key="version"):
    # None rather than an exception on a missing key or a parse failure, so the
    # assertion below reports what to do instead of a bare KeyError.
    try:
        return str(yaml.safe_load(path.read_text())[key])
    except (KeyError, TypeError, yaml.YAMLError):
        return None


def from_json_key(path, key="version"):
    try:
        return str(json.loads(path.read_text())[key])
    except (KeyError, TypeError, json.JSONDecodeError):
        return None


def from_regex(path, pattern):
    match = re.search(pattern, path.read_text(), flags=re.MULTILINE)
    return match.group(1) if match else None


# (relative path, how to read its version, where its version comes from). The origin
# is quoted in the failure message so a partial build reads differently from a file
# the release action failed to rewrite.
CASES = [
    (
        "CITATION.cff",
        from_yaml_key,
        "hand-maintained, written by the release action",
    ),
    (
        ".zenodo.json",
        from_json_key,
        "hand-maintained, written by the release action",
    ),
    (
        "release/README.md",
        lambda p: from_regex(p, r"Current version: \[MIxS v([0-9][^\]]*)\]"),
        "hand-maintained, written by the release action",
    ),
    (
        "project/mixs.yaml",
        from_yaml_key,
        "generated: copied from the source schema by make gen-project",
    ),
    (
        "project/jsonschema/mixs.schema.json",
        from_json_key,
        "generated by make gen-project",
    ),
    (
        "project/jsonld/mixs.jsonld",
        from_json_key,
        "generated by make gen-project",
    ),
    (
        "project/owl/mixs.owl.ttl",
        lambda p: from_regex(p, r'pav:version\s+"([^"]+)"'),
        "generated by make owl",
    ),
    (
        "src/mixs/datamodel/mixs.py",
        lambda p: from_regex(p, r'^version = "([^"]+)"'),
        "generated by make gen-project",
    ),
]


class TestVersionConsistency(unittest.TestCase):
    """unittest rather than pytest, because CI runs `python -m unittest discover`."""

    def test_every_version_string_matches_the_source_schema(self):
        expected = schema_version()
        for relative_path, read_version, origin in CASES:
            with self.subTest(path=relative_path):
                path = ROOT / relative_path
                # Failing rather than skipping: a missing file here means a generated
                # artifact was deleted or a build did not run, and skipping would let
                # that pass CI silently, which is the thing this test exists to stop.
                self.assertTrue(
                    path.exists(),
                    f"{relative_path} is missing. It should be committed. If it is a "
                    f"generated file, run `make all`. Origin: {origin}.",
                )

                found = read_version(path)

                self.assertIsNotNone(
                    found,
                    f"No version string could be read from {relative_path}. Its format "
                    f"probably changed, which also means the release action's sed no "
                    f"longer matches it and is silently doing nothing. "
                    f"Origin: {origin}.",
                )
                self.assertEqual(
                    found,
                    expected,
                    f"{relative_path} says {found}, but src/mixs/schema/mixs.yaml says "
                    f"{expected}. Origin: {origin}. Every file carrying a MIxS version "
                    f"must carry the same one, and it must match the release tag.",
                )

    def test_source_schema_version_is_a_bare_semver(self):
        """No leading v: the v belongs to the git tag, not to file content."""
        version = schema_version()
        self.assertRegex(
            version,
            r"^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$",
            f"src/mixs/schema/mixs.yaml declares version {version!r}. It should be a "
            f"bare X.Y.Z, optionally with a pre-release suffix, and never carry a "
            f"leading 'v'.",
        )


if __name__ == "__main__":
    unittest.main()
