"""Every file that carries a MIxS version string must carry the same one.

The release action writes the version into some of these with `sed -i`, which exits
0 whether or not its pattern matched. If one of these files is reformatted, the sed
silently changes nothing and the release ships a stale version with no error. The
rest inherit the version from src/mixs/schema/mixs.yaml when `make` regenerates them,
so they only disagree if a build was skipped or partial.

pyproject.toml is excluded on purpose: it holds a 0.0.0 placeholder and the Python
package version comes from the git tag at build time.
"""

import json
import re
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]

SOURCE_SCHEMA = ROOT / "src" / "mixs" / "schema" / "mixs.yaml"


def schema_version():
    return str(yaml.safe_load(SOURCE_SCHEMA.read_text())["version"])


def from_yaml_key(path, key="version"):
    return str(yaml.safe_load(path.read_text())[key])


def from_json_key(path, key="version"):
    return str(json.loads(path.read_text())[key])


def from_regex(path, pattern):
    match = re.search(pattern, path.read_text(), flags=re.MULTILINE)
    return match.group(1) if match else None


# Each entry is (relative path, how to read its version). Generated files are marked
# so a partial build gives a clearer failure message than a bare mismatch.
CASES = [
    ("CITATION.cff", lambda p: from_yaml_key(p), "hand-maintained, written by the release action"),
    (".zenodo.json", lambda p: from_json_key(p), "hand-maintained, written by the release action"),
    (
        "release/README.md",
        lambda p: from_regex(p, r"Current version: \[MIxS v([0-9][^\]]*)\]"),
        "hand-maintained, written by the release action",
    ),
    ("project/mixs.yaml", lambda p: from_yaml_key(p), "generated: copied from the source schema"),
    (
        "project/jsonschema/mixs.schema.json",
        lambda p: from_json_key(p),
        "generated by make gen-project",
    ),
    (
        "project/jsonld/mixs.jsonld",
        lambda p: from_json_key(p),
        "generated by make gen-project",
    ),
    (
        "project/owl/mixs.owl.ttl",
        lambda p: from_regex(p, r'pav:version\s+"([^"]+)"'),
        "generated by make owl",
    ),
    (
        "src/mixs/datamodel/mixs.py",
        lambda p: from_regex(p, r'^version = "([^"]+)"', ),
        "generated by make gen-project",
    ),
]


@pytest.mark.parametrize(
    "relative_path,read_version,origin", CASES, ids=[c[0] for c in CASES]
)
def test_version_matches_the_source_schema(relative_path, read_version, origin):
    path = ROOT / relative_path
    if not path.exists():
        pytest.skip(f"{relative_path} is not present in this checkout")

    expected = schema_version()
    found = read_version(path)

    assert found is not None, (
        f"No version string could be read from {relative_path}. Its format probably "
        f"changed, which also means the release action's sed no longer matches it and "
        f"is silently doing nothing. Origin: {origin}."
    )
    assert found == expected, (
        f"{relative_path} says {found}, but src/mixs/schema/mixs.yaml says {expected}. "
        f"Origin: {origin}. Every file carrying a MIxS version must carry the same one, "
        f"and it must match the release tag."
    )


def test_source_schema_version_is_a_bare_semver():
    """No leading v, since the v belongs to the git tag and not to file content."""
    version = schema_version()
    assert re.fullmatch(r"\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?", version), (
        f"src/mixs/schema/mixs.yaml declares version {version!r}. It should be a bare "
        f"X.Y.Z, optionally with a pre-release suffix, and never carry a leading 'v'."
    )
