---
name: LinkML Linting GitHub Action
on:
  push:
    paths:
      - "src/mixs/schema/mixs.yaml"
jobs:
  linkml:
    permissions:
      contents: write
      pull-requests: write
    name: LinkML Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install linkml

      - name: Run LinkML Linting
        run: |
          ## Results file header and basic formatting
          printf '# LinkML Linting Results \n\n' > linting-results.md
          printf "$(linkml --version) linting found the following issues. \n\n" >> linting-results.md
          printf "_For more information about the linting rule categories, see the [LinkML linter documentation](https://linkml.io/linkml/schemas/linter.html#rules)._\n" >> linting-results.md
          ## Lint the schema, and further format
          linkml lint --config linkml-lint-config.yml --ignore-warnings -f markdown src/mixs/schema/mixs.yaml >> linting-results.md
      - name: Reformat log
        run: |
          sed -z -i -e 's/#### Errors/> [!CAUTION]/' -e 's/#### Warnings/<details>> [!WARNING]/' -e 's/^*/> */' -e '/###.*yaml/ s/$/\n/' -e '/###.*yaml/ s/^###/**File**:/' -e '$a</details>' linting-results.md
      - name: Post PR comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-path: linting-results.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
