name: Preview documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    # Only run on PRs from the main repository, not forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1

      - name: Install dependencies
        run: make install

      - name: Generate web-based documentation
        run: |
          make clean
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          poetry run mkdocs build -d site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1
        with:
          source-dir: site/
          preview-branch: gh-pages